# Generated by Django 3.1.3 on 2020-11-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetodo', '0004_task_task_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(),
        ),
    ]
